export default  [
    {   "id":1,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"If they said so, I really don't remember. I was upset.",
        "context":"Andy's Resopnds to the district attorney when the D.A. informs Andy about his neighbor's testimony."
    },
    {   "id":2,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"Since I am innocent of this crime, sir, I find it decidedly inconvenient that the gun was never found.",
        "context":"Andy's Reactions to the district attorney when the D.A. implied Andy's aliby is 'too conveinet'."
    },
    {   "id":3,
        "character":"1946 Judge",
        "cast":"John Horton",
        "quote":"You strike me as a particularly icy and remorseless man, Mr.Dufresne. It chills my blood just to look at you.",
        "context":"Judge's final remarks of Andy before he close the case."
    },
    {   "id":4,
        "character":"1947 Judge",
        "cast":"John Horton",
        "quote":"I hereby order you to serve two life sentences, back to back. One for each of your victims. So be it.",
        "context":"Judge's delivery for closing the case."
    },
    {   "id":5,
        "character":"1947 Parole Hearings Man",
        "cast":"Gordon Greene",
        "quote":"You feel you've been rehabilitated?",
        "context":"Parole board member's first question toward Red at 1947, first jail scene."
    },
    {   "id":6,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I can honestly say I'm a changed man. No longer danger to society. That's God's honest truth.",
        "context":"Red's answers to the parole board."
    },
    {   "id":7,
        "character":"Warden Norton",
        "cast":"Bob Gunton",
        "quote":"I believe in two things, discipline and the Bible. Here, you'll receive both. Put your trust in the Lord. Your ass belongs to me. ",
        "context":"Warden Norton's speech to Andy and the other newcomers upon their arrival in Shawshank."
    },
    {   "id":8,
        "character":"Warden Norton",
        "cast":"Bob Gunton",
        "quote":"Welcome to Shawshank.",
        "context":"Warden Norton's welcome toward Andy and other newcomers, marking the start of their new lives in jail."
    }
    {   "id":9,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Old life blown away in the blink of an eye. Nothing left, but all the time in the world to think about it.",
        "context":"Red's thoughts about the 'first night' in jail, just before lights out."
    },
    {   "id":10,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I remember my first night. Seems like a long time ago.",
        "context":"Red's thoughts about the 'first night' in jail, just before lights out."
    },
    {   "id":11,
        "character":"Fat Ass",
        "cast":"Frank Medrano",
        "quote":"God! I don't belong here. I wanna go home. I want my mommy.",
        "context":"Cries from the fat ass, winning boxes of cigarettes for Heywood."
    },
    {   "id":12,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"His first night in the joint, Andy Dufresne cost me two packs of cigarettes. He never made a sound.",
        "context":"Red's thoughts toward Andy, after Andy's 'first night' in jail. Red lost his bet with the cons."
    },
    {   "id":13,
        "character":"Heywood",
        "cast":"William Sadler",
        "quote":"Why do you care, new fish?",
        "context":"Heywood's reaction when Andy asked for the dead fat ass's name."
    },
    {   "id":14,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Everybody here is innocent, you didn't know that?",
        "context":"Red's reactions while having the first conversation with Andy. Andy said he was innocent."
    },
    {   "id":15,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"You have to be human first. They don't qualify.",
        "context":"Red's comments about the 'sisters', warning Andy to watch his back."
    },
    {   "id":16,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Mention my name, we never do business again.",
        "context":"Red's warning to Andy, after he agreed to get Andy a stonehammer."
    },
    {   "id":17,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"He strolled lika a main in a park without a care or worry in the world. Like he had on an invisible coat that would shield him from this place.",
        "context":"Red's comments about Andy, after their first conversation."
    },
    {   "id":18,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"He never said who did it, but we all knew.",
        "context":"Red's thoughts about Andy's bruises. Andy got those bruises in fights with the 'sisters'."
    },
    {   "id":19,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Prison life consists of routine...and then more routine.",
        "context":"Red's comments about jail life, after worring about Andy. Andy's routine was to fight off the 'sisters'."
    },
    {   "id":20,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"I think a man working outdoors feels more like a man if he can have a bottle of suds.",
        "context":"Andy's request to captain Hadley, Andy teach Hadley to evade taxes in exchange for getting beers for the cons."
    },
    {   "id":21,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"I understand you're a man that knows how to get things.",
        "context":"What Andy always said to Red, when Andy makes request to Red."
    },
    {   "id":22,
        "character":"Heywood",
        "cast":"William Sadler",
        "quote":"Sounds good to us. I figure we owe him that much for the beer.",
        "context":"Heywood's reaction when Andy is about to get back from infirmary. "
    },
    {   "id":23,
        "character":"Heywood",
        "cast":"William Sadler",
        "quote":"Oh!Jesus!",
        "context":"Heywood's reaction when he find a 'horse apple'."
    },
    {   "id":24,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"No Charge. Welcome Back.",
        "context":"(Red's handwriting for Andy, showing welcome when Andy got back from infirmary.)"
    },
    {   "id":25,
        "character":"Warden Norton's wife",
        "cast":"Unknown",
        "quote":"His Judgement Cometh and that Right Soon",
        "context":"(Warden Norton's wife make this needlework in church group.)"
    },
    {   "id":26,
        "character":"Brooks Hatlen",
        "cast":"James Whitmore",
        "quote":"Easy-peasy, Japanesey. Any question?",
        "context":"Brooks asked Andy if there's any question. After Andy was assigned to Brook's libray."
    },
    {   "id":27,
        "character":"Andy Dufresne ",
        "cast":"Tim Robbins",
        "quote":"So, Mr.Dekins do you want your sons to go to Harvard, or Yale?",
        "context":"Andy asked office mr.Dekins where mr.Dekins want to send his sons to, using the trust fund they would set up."
    },
    {   "id":28,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"In here, he is an important man. He's an educated man. Outside, he's nothing.",
        "context":"Red's explaination to the cons who were wondering why Brooks rufused to leave Shawshank."
    },
    {   "id":29,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I am telling you these walls are funny. First you hate 'emthen you get used to 'em. Enough time passes, your get so you depend on 'em.",
        "context":"Red's explaination about the 'institutionalized'."
    },
    {   "id":30,
        "character":"Brooks Hatlen",
        "cast":"James Whitmore",
        "quote":"BROOKS WAS HERE",
        "context":"(Brook's messages left in the halfway house 'The Brewer'.)"
    },
    {   "id":31,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I tell you, those voices soaredhigher and farther than anybody in a grey place dares to dream. It was like some beautiful bird flapped into our drab little cage and made those walls dissolve away.",
        "context":"Red's thoughts when he heard Andy played the record of 'Duettino from the marriage of figaro'."
    },
    {   "id":32,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"And for the briefest of momentsevery last man at Shawshank felt free.",
        "context":"Red's comments after he heard Andy played the record of 'Duettino from the marriage of figaro'."
    },
    {   "id":33,
        "character":"Heywood",
        "cast":"William Sadler",
        "quote":"Y-Y-You couldn't play something good, huh? Hank Williams or something?",
        "context":"What Heywood said Andy after Andy ended his solitary confinement. He was in there for a month."
    },
    {   "id":34,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"That's the beauty of music. They can't get that from you",
        "context":"Andy thoughts about music, elaborating why he played the phonograph record."
    },
    {   "id":35,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"You need it, so you don't forget. Forget that there are places in the world that aren't made out of stonethere is something inside that they can't get to, they can't touch.",
        "context":"Andy thoughts about music, elaborating why he played the phonograph record."
    },
    {   "id":36,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"A NEW Girl For Your 10 Year ANNIVERSARY",
        "context":"(Red's handwriting for Andy, Red gave Andy a new poster of Marilyn Monroe.)"
    },
    {   "id":37,
        "character":"Heywood",
        "cast":"William Sadler",
        "quote":"The Count Of Monte Crisco. By Alexandree Dumass. Dumbass?",
        "context":"Heywood trying to help Andy to sort books by genre or subject area."
    },
    {   "id":38,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"You know, the funny thing is, on the outside, I was an honest man, straight as an arrow. I have to come to prison to be a crook.",
        "context":"What Andy said to Red after Andy explained how exactly he helped Norton to laundry his money."
    },
    {   "id":39,
        "character":"Andy Dufresne",
        "cast":"Tim Robbin",
        "quote":"Me? Lawyer fucked me. Everybody here is innocent, you don't know that?",
        "context":"Andy's responds about his murder case, to Tommy Williams, a newmember of Shawshank."
    },
    {   "id":40,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"Zihuatanejo.",
        "context":"Andy revealed the place he wants to go after getting out from Shawshank."
    },
    {   "id":41,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I don't think I could make it on the outside, Andy.",
        "context":"Red's responds to Andy, after Andy asked Red to come with him to Zihuatanejo."
    },
    {   "id":42,
        "character":"Andy Dufresne",
        "cast":"Andy Dufresne",
        "quote":"Get busy living, or get busy dying.",
        "context":"What Andy said before the night he escaped from Shawshank."
    },
    {   "id":43,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Every man has his breaking point.",
        "context":"What Red said to the cons, after knowing Andy got a rope from Heywood. Andy escaped at that night."
    },
    {   "id":44,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Alone in the dark with nothing but your thoughts, time can draw out like a blade.",
        "context":"Red's anxious feelings about that Andy might commit suicide."
    },
    {   "id":45,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Andy crawled to freedom through 500 yards of shit-smelling foulness I can't even imagine. Or maybe I just don't want to.",
        "context":"Funny narration by Red."
    },
    {   "id":46,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I guess I just miss my friend.",
        "context":"Red's feelings after Andy escaped from Shawshank."
    },
    {   "id":47,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"Rehabilitated? Well now let me see. Y'know I don't have no idea what it means.",
        "context":"Red's answers to the parole board. This time, he answered differently."
    },
    {   "id":48,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"There's not a day goes by I don't feel regret. Not because I'm in here or because you think I should. I look back on the way I was then. A young stupid kid  commited a terrible crime. I want to talk to him. I wanna try and talk some sense to him, tell him the way things are, but I can't. That kid's long gone. This old man is all that's left, I gonna live with that.",
        "context":"Red's answers to the parole board. After the parole member asked Red if he is sorry for what he did."
    },
    {   "id":49,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"All I want is be back where things make sense, where I won't have to be afraid all the time. Only one thing stops me. A promise I made to Andy.",
        "context":"After Red got out from the jail, he was lonely."
    },
    {   "id":50,
        "character":"Andy Dufresne",
        "cast":"Tim Robbins",
        "quote":"Remember Red, hope is a good thing. Mayber the best of things. And no good thing ever dies.",
        "context":"What Andy wrote in the letter, addressed to Red."
    },
    {   "id":51,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"BROOKS WAS HERE AND SO WAS RED",
        "context":"(Red add his name next to Brook's messages before he head off to Zihuatanejo.)"
    },
    {   "id":52,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I find I'm so excited I can barely sit still or hold a thought in my head. I think this is the excitement only a freeman could feel. A free man at the start of a long journey whose conclusion is uncertain.",
        "context":"Red's feelings on his way to Zihuatanejo."
    },
    {   "id":53,
        "character":"Ellis Boyd 'Red' Redding",
        "cast":"Morgan Freeman",
        "quote":"I hope I can make it across the border. I hope I can see my friend and shake his hand. I hope the Pacific is as blue as it has been in my dreams. I hope.",
        "context":"Red's feelings on his way to Zihuatanejo, looking forward to see Andy."
    },
]
